// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table ride_events (ride_id:guid, event_ts:datetime, pickup_zone_id:string, dropoff_zone_id:string, status:string, surge_multiplier:real, eta_minutes:int, fare_estimate:real) 
.create-or-alter table ride_events ingestion json mapping 'ride_events_mapping'
```
[{"Properties":{"Path":"$['ride_id']"},"column":"ride_id","datatype":""},{"Properties":{"Path":"$['event_ts']"},"column":"event_ts","datatype":""},{"Properties":{"Path":"$['pickup_zone_id']"},"column":"pickup_zone_id","datatype":""},{"Properties":{"Path":"$['dropoff_zone_id']"},"column":"dropoff_zone_id","datatype":""},{"Properties":{"Path":"$['status']"},"column":"status","datatype":""},{"Properties":{"Path":"$['surge_multiplier']"},"column":"surge_multiplier","datatype":""},{"Properties":{"Path":"$['eta_minutes']"},"column":"eta_minutes","datatype":""},{"Properties":{"Path":"$['fare_estimate']"},"column":"fare_estimate","datatype":""}]
```
